services: 
  terraria-server:
    image: hexlo/terraria-server-docker:latest
    container_name: terraria-server
    restart: unless-stopped
    stdin_open: true
    tty: true     
    ports:
      - 7779:7777
    volumes:
      - type: bind
        source: ./Worlds
        target: /root/.local/share/Terraria/Worlds
    environment:
      # - world=/root/.local/share/Terraria/Worlds/newworld.wld
      - autocreate=2
      - difficulty=2
      - worldname=newworld
      - password=hello
      - motd="Welcome to my server! :)"
