name: terraria
services:
  server:
    build:
      context: ./build
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 7777:7777
    volumes:
      - ./worlds:/opt/terraria/Worlds
      - ./config/server-config.conf:/opt/terraria/server-config.conf
      - ./config/banlist.txt:/opt/terraria/banlist.txt
    environment:
      TERRARIA_VERSION: latest
